- name: New AKS Cluster
  hosts: localhost
  connection: local
  vars:
    AKS_resource_group: AKSDemo1
    AKS_location: "East Asia"
    aks_name: aksclus
    username: aksuser
    ssh_pub_key: ""
    client_secret: ""
    k8s_version: "1.23.3"

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ AKS_resource_group }}"
        location: "{{ AKS_location }}"
    - name: Create an AKS cluster
      azure_rm_aks:
        name: "{{ aks_name }}"
        location: "{{ AKS_location }}"
        kubernetes_version: "{{ k8s_version }}"
        resource_group: "{{ AKS_resource_group }}"
        dns_prefix: "mynewcluster"
        linux_profile:
          admin_username: "{{ username }}"
          ssh_key: "{{ ssh_pub_key }}"
        service_principal:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
        agent_pool_profiles:
          - name: default
            count: 1
            vm_size: Standard_B2s
            mode: System
        tags:
          Environment: "Dev"
          Backup: "False"
          Client: "Mike"
